before_install: []
env:
  global: []
install:
  - 'a() { set -e; }'
  - "z() { E=$?; test $E -eq 0 && return 0; printf \"\\n\\033[1;31mThe command failed with exit code $?.\\033[0m\"; set -e; return $E; }"
  - (a; sudo pip2 install nose );z
script:
  - (a; sudo python setup.py install );z
  - |-
    (a; cd tests
    nosetests
     );z
git:
  depth: 10
language: objective-c
notifications:
  email: false
matrix:
  fast_finish: true
branches:
  only:
    - master
