before_install: []
env:
  global:
    - TEST_SPEEDUP=10
    - TEST_RATE=200
    - TEST_RETRY=1
install:
  - 'a() { set -e; }'
  - "z() { E=$?; test $E -eq 0 && return 0; printf \"\\n\\033[1;31mThe command failed with exit code $?.\\033[0m\"; set -e; return $E; }"
  - (a; sudo pip2 install nose psutil mock );z
  - '(a; sudo pip2 install git+https://github.com/3drobotics/dronekit-sitl-runner.git );z'
script:
  - (a; sudo python setup.py install );z
  - (a; [ "${TRAVIS_PULL_REQUEST}" != "false" ] || nosetests tests/web );z
  - (a; nosetests tests/unit );z
  - (a; python -m tests.sitl );z
git:
  depth: 10
language: objective-c
notifications:
  email: false
matrix:
  fast_finish: true

branches:
  only:
    - master
    - patch
    - major
    - minor
