environment:
  global:
    TEST_SPEEDUP: 10
    TEST_RATE: 200
    TEST_RETRY: 4
init: []
cache:
  - "c:\\Users\\appveyor\\.pip-wheelhouse"
install:
  - ps: |
      New-Item -ItemType Directory -Force -Path c:\Users\appveyor\pip\
      @'
      [global]
      find-links = file://c:/Users/appveyor/.pip-wheelhouse

      [wheel]
      wheel-dir = c:/Users/appveyor/.pip-wheelhouse
      '@ | out-file -Encoding ascii -FilePath c:\Users\appveyor\pip\pip.ini
  - cmd: 'setlocal & python -m pip install pip wheel -U & endlocal'
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 wheel numpy & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 install nose numpy psutil mock & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 install git+https://github.com/3drobotics/dronekit-sitl-runner.git & endlocal"

  - cmd: choco install innosetup
  - cmd: cd windows & droneapiWinBuild.bat
  - ps: |
      Invoke-WebRequest "http://firmware.diydrones.com/Tools/MAVProxy/MAVProxySetup-latest.exe" -OutFile MAVProxySetup-latest.exe
      .\MAVProxySetup-latest.exe /VERYSILENT /LOG=setup-mavproxy.log
      while (!(Test-Path "setup-mavproxy.log")) { Start-Sleep 1 }
      while(!(Select-String -path 'setup-mavproxy.log' -pattern 'Log closed' -quiet)){ Start-Sleep 1 };
      rm ~\AppData\Local\MAVProxy\mavinit.scr
  - ps: |
      $setup = gi .\windows\Output\DroneKitsetup-*.exe
      & $setup /VERYSILENT /LOG=setup-dronekit.log
      while (!(Test-Path "setup-dronekit.log")) { Start-Sleep 1 }
      while(!(Select-String -path 'setup-dronekit.log' -pattern 'Log closed' -quiet)){ Start-Sleep 1};

build_script:
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;c:\\Program Files (x86)\\MAVProxy;%PATH% & python -m tests.sitl & endlocal"
  - cmd: 'setlocal & python setup.py install & endlocal'
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & nosetests tests\\web & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & nosetests tests\\unit & endlocal"
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -and ($env:APPVEYOR_REPO_TAG_NAME -match '^v\d+\.\d+\.\d+$')) {
        echo "Publishing installer."
        $setup = gi .\windows\Output\DroneKitsetup-*.exe
        aws s3 cp $setup s3://dronekit-installers/windows/dronekit-windows-$env:APPVEYOR_REPO_TAG_NAME.exe --acl public-read
        aws s3 cp $setup s3://dronekit-installers/windows/dronekit-windows-latest.exe --acl public-read
      } else {
        echo "Skipping publishing installer on non-tag."
      }

clone_depth: 10
test: 'off'
branches:
  only:
    - master
    - major
    - minor
    - patch
    - /^v\d+\.\d+\.\d+$/
