environment:
  global:
    TEST_SPEEDUP: 10
    TEST_RATE: 200
    TEST_RETRY: 4
init: []
cache:
  - "c:\\Users\\appveyor\\.pip-wheelhouse"
install:
  - ps: |
      New-Item -ItemType Directory -Force -Path c:\Users\appveyor\pip\
      @'
      [global]
      find-links = file://c:/Users/appveyor/.pip-wheelhouse

      [wheel]
      wheel-dir = c:/Users/appveyor/.pip-wheelhouse
      '@ | out-file -Encoding ascii -FilePath c:\Users\appveyor\pip\pip.ini
  - cmd: 'setlocal & python -m pip install pip wheel -U & endlocal'
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 wheel numpy & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 install nose numpy psutil mock & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 install git+https://github.com/3drobotics/dronekit-sitl-runner.git & endlocal"
build_script:
  - cmd: 'setlocal & python setup.py install & endlocal'
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & nosetests tests\\web & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & nosetests tests\\unit & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & cd tests & python -um sitl & endlocal"
clone_depth: 10
test: 'off'
branches:
  only:
    - master
